# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jvconsultacontroller',
            fields=[
                ('id_tipo_sensor', models.IntegerField(primary_key=True, serialize=False)),
                ('sensor', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(null=True)),
            ],
        ),
    ]
